package th.co.aerothai.nanon.model;

import java.time.LocalDateTime;

import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// Represents a User entity in the system.
// * Mapped directly to the 'APP_USERS' table in the database.
// * Uses Lombok to auto-generate getters, setters, constructors, and toString methods.
@Entity
@Table(name = "APP_USERS")
@Data
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class User {

    // Unique ID for the user.
    // * Auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // The full name of the user.
    // * Cannot be null.
    @Column(nullable = false)
    private String name;

    // The email address of the user.
    // * Must be unique and cannot be null.
    @Column(nullable = false, unique = true)
    private String email;

    // The role assigned to the user
    private String role;

    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(nullable = false)
    private LocalDateTime updatedAt;
}
